### PR TITLE
Add remote cleanup

### PR DESCRIPTION
**Pull request by juliangruber**
Example:

``` js
exports.remote = function(trace){
  var id = setInterval(function(){
    // ...
  });

  return function unsubscribe(){
    clearInterval(id);
  };
};
```

If this looks good, I'll add docs

### CODE REVIEW

**Comment by tj** [comment]
I like the "cleanup" event idea, might be a little ambiguous with other events I guess but I dig that more than returning a function

**Comment by tj** [comment]
rest LGTM!

**Comment by juliangruber** [comment]
ok, I'll change that

**Comment by juliangruber** [comment]
done

**Comment by tj** [comment]
squashed and merged!

**Comment by juliangruber** [comment]
kick ass!

**Pull request closed without merging**
